# Generated by Django 2.1.1 on 2018-09-17 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_num', models.CharField(max_length=50, verbose_name='Numéro de facture')),
                ('entry_date', models.DateField(auto_now=True)),
                ('object', models.TextField(max_length=150, verbose_name='Objet')),
                ('bill_type', models.CharField(max_length=100, verbose_name='Type de facture')),
                ('decision_ST', models.IntegerField(choices=[('1', 'Non Traiter'), ('2', 'Accepter'), ('3', 'Refuser')], default='1')),
                ('penalty_rate', models.FloatField(default=0, verbose_name='taux de pénalité')),
                ('ht_amount', models.FloatField(verbose_name='Montant HT')),
                ('other_coasts', models.FloatField(default=0, verbose_name='Autres frais')),
                ('decision_FC', models.IntegerField(choices=[('1', 'Non Traiter'), ('2', 'Accepter'), ('3', 'Refuser')], default='1')),
                ('transfer_order', models.CharField(blank=True, max_length=20, verbose_name='Ordre de virement')),
                ('billing_date', models.DateField(verbose_name='Date de facturation')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_designation', models.CharField(max_length=50, verbose_name='Designation du district')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('1', 'Madame'), ('2', 'Monsieur'), ('3', 'Mademoiselle')], default='2', max_length=1, verbose_name='Genre')),
                ('provider_last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('provider_first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('provider_address', models.CharField(max_length=150, verbose_name='Addrese')),
                ('email', models.EmailField(max_length=254)),
                ('fixed_phone', models.CharField(max_length=9, verbose_name='Téléphone fix')),
                ('mobile_phone', models.CharField(max_length=10, verbose_name='Téléphone mobile')),
                ('rib', models.CharField(max_length=20, verbose_name='RIB')),
                ('nif', models.CharField(max_length=20, verbose_name='NIF')),
                ('r_commerce', models.CharField(max_length=20, verbose_name='raison Comercial')),
            ],
        ),
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('rejection_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=30, verbose_name='Motif de rejet')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50, verbose_name='Designation du service')),
                ('service_abv', models.CharField(max_length=10, verbose_name='Abreviation du service')),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('slip_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id du bordereau')),
                ('slip_num', models.IntegerField(verbose_name='Numéro du bordereau')),
                ('closed', models.BooleanField(default=False)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='billingManager.Service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('town_id', models.AutoField(primary_key=True, serialize=False)),
                ('town_name', models.CharField(max_length=30, verbose_name='Nom de la ville')),
                ('postal_code', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Code postal')),
            ],
        ),
        migrations.CreateModel(
            name='TVA',
            fields=[
                ('tva_id', models.AutoField(primary_key=True, serialize=False)),
                ('tva_rate', models.FloatField(verbose_name='Taux de TVA')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_auth', models.OneToOneField(on_delete='CASCADE', primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('user_first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('mobile_phone', models.CharField(max_length=9, verbose_name='Téléphone portable')),
                ('born_date', models.DateField(verbose_name='Date de naissance')),
                ('years_seniority', models.IntegerField(verbose_name="Années d'ancienneté")),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='town',
            field=models.ForeignKey(on_delete='CASCADE', to='billingManager.Town', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='bill',
            name='district',
            field=models.ForeignKey(on_delete='CASCADE', to='billingManager.District', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='bill',
            name='provider',
            field=models.ForeignKey(on_delete='CASCADE', to='billingManager.Provider', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='bill',
            name='rejection_reasonFC',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='motif2', to='billingManager.RejectionReason', verbose_name='Raison de rejet du service comptabilité et finance'),
        ),
        migrations.AddField(
            model_name='bill',
            name='rejection_reasonST',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='motif1', to='billingManager.RejectionReason', verbose_name='Raison de rejet du service traitant'),
        ),
        migrations.AddField(
            model_name='bill',
            name='service',
            field=models.ForeignKey(on_delete='CASCADE', to='billingManager.Service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='bill',
            name='slip',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='billingManager.Slip', verbose_name='Nu,éro du bordereau'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tva',
            field=models.ForeignKey(on_delete='CASCADE', to='billingManager.TVA', verbose_name='Taux de TVA'),
        ),
    ]
