# Generated by Django 2.0 on 2018-09-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='slip',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='billingManager.Slip', verbose_name='Numéro du bordereau'),
        ),
    ]
