# Generated by Django 2.0 on 2018-09-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingManager', '0002_auto_20180918_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSlip',
            fields=[
                ('slip_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id du bordereau')),
                ('slip_num', models.IntegerField(verbose_name='Numéro du bordereau')),
                ('closed', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=1, verbose_name='Valide')),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='decision_FC',
            field=models.CharField(choices=[('1', 'Non traitée'), ('2', 'Acceptée'), ('3', 'Rejetée')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='decision_ST',
            field=models.CharField(choices=[('1', 'Non traitée'), ('2', 'Acceptée'), ('3', 'Rejetée')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billingManager.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billingManager.Provider', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rejection_reasonFC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motif2', to='billingManager.RejectionReason', verbose_name='Raison de rejet du service comptabilité et finance'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rejection_reasonST',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motif1', to='billingManager.RejectionReason', verbose_name='Raison de rejet du service traitant'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billingManager.Service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='slip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billingManager.Slip', verbose_name='Nu,éro du bordereau'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billingManager.TVA', verbose_name='Taux de TVA'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billingManager.Town', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='slip',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billingManager.Service', verbose_name='Service'),
        ),
    ]
