# Generated by Django 2.0 on 2018-09-23 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingManager', '0003_auto_20180921_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='decision_BO',
            field=models.CharField(choices=[('1', 'Non Traiter'), ('2', 'Accepter'), ('3', 'Refuser')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='bill',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billingManager.UserProfile', verbose_name='Saisie par'),
        ),
        migrations.AddField(
            model_name='bill',
            name='rejection_reasonBO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motif1', to='billingManager.RejectionReason', verbose_name="Raison de rejet d  u bureau d'ordre"),
        ),
        migrations.AlterField(
            model_name='bill',
            name='decision_FC',
            field=models.CharField(choices=[('1', 'Non Traiter'), ('2', 'Accepter'), ('3', 'Refuser')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='decision_ST',
            field=models.CharField(choices=[('1', 'Non Traiter'), ('2', 'Accepter'), ('3', 'Refuser')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rejection_reasonFC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motif3', to='billingManager.RejectionReason', verbose_name='Raison de rejet du service comptabilité et finance'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rejection_reasonST',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motif2', to='billingManager.RejectionReason', verbose_name='Raison de rejet du service traitant'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='slip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billingManager.Slip', verbose_name='Numéro du bordereau'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
