# Generated by Django 2.0 on 2018-09-23 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingManager', '0004_auto_20180923_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Saisie par'),
        ),
    ]
