# Generated by Django 2.0 on 2018-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingManager', '0005_auto_20180923_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='born_date',
            field=models.DateField(blank=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=9, verbose_name='Téléphone portable'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='years_seniority',
            field=models.IntegerField(blank=True, verbose_name="Années d'ancienneté"),
        ),
    ]
