# Generated by Django 2.0 on 2018-09-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingManager', '0006_auto_20180923_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billingManager.UserProfile', verbose_name='Saisie par'),
        ),
    ]
