# Generated by Django 2.0 on 2018-09-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingManager', '0009_auto_20180923_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='service_slip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billingManager.ServiceSlip', verbose_name='Numéro du bordereau de service traitant'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billingManager.District', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billingManager.Service', verbose_name='Service'),
        ),
    ]
