# Generated by Django 2.0 on 2018-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingManager', '0011_auto_20180926_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='district_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='service_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type de facture'),
        ),
        migrations.AlterField(
            model_name='rejectionreason',
            name='reason',
            field=models.CharField(max_length=100, verbose_name='Motif de rejet'),
        ),
    ]
