# Generated by Django 2.0 on 2018-10-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingManager', '0012_auto_20180930_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ('-entry_date',)},
        ),
    ]
